sudo: required
dist: trusty

language: python
python:
  - "3.6"

before_install:
- sudo apt-get install ffmpeg & ffmpeg -version

script:
- pip install path.py
- python -m py_compile clean-deploy.py

after_success:
- git clone https://github.com/fossasia/labyrinth target
- python clean-deploy.py